name: ABI Workflow
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Check versions
        run: |
          node --version
          npm --version
      - name: Greet me
        run: ./github/scripts/my-fn.js
        env:
          NAME: ${{ github.event.repository.name }}
